---
abstract: 'inject content from one HTML file into another'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
  XML::LibXML::PrettyPrint: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::Inject
name: HTML-Inject
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  HTML::HTML5::Writer: 0
  XML::LibXML::PrettyPrint: 0
requires:
  HTML::HTML5::Parser: 0.200
  IO::Detect: 0
  Moo: 1.000000
  Scalar::Does: 0.002
  XML::LibXML: 1.94
  namespace::sweep: 0.006
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-Inject
  homepage: https://metacpan.org/release/HTML-Inject
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-html-inject
version: 0.003
x_contributors:
  - 'Andreas J. König <ANDK@cpan.org>'
