---
abstract: 'inject content from one HTML file into another'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
  XML::LibXML::PrettyPrint: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::8 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Inject
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  HTML::Inject:
    file: lib/HTML/Inject.pm
    version: '0.004'
recommends:
  HTML::HTML5::Writer: '0'
  XML::LibXML::PrettyPrint: '0'
requires:
  HTML::HTML5::Parser: '0.200'
  IO::Detect: '0'
  Moo: '1.000000'
  Scalar::Does: '0.002'
  XML::LibXML: '1.94'
  namespace::sweep: '0.006'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/HTML-Inject/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-Inject
  homepage: https://metacpan.org/release/HTML-Inject
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-html-inject.git
version: '0.004'
